// All action types

const interview = {
  REQUEST_QUESTIONS: 'REQUEST_QUESTIONS',
  RECEIVE_QUESTIONS: 'RECEIVE_QUESTIONS',
  NEXT_QUESTION: 'NEXT_QUESTION',
  CORRECT_ANSWER: 'CORRECT_ANSWER',
  REQUEST_USERDATA: 'REQUEST_USERDATA',
  RECEIVE_USERDATA: 'RECEIVE_USERDATA'
};

export default interview;
